idf_component_register(
    SRCS
        "main.c"
        "board.c"
        "touch.c"
        "imu.c"
        "button.c"
        "audio.c"
        "synth.c"
        "gfx.c"
        "font.c"
        "game.c"
        "guard.c"
        "level.c"
        "render.c"
        "hud.c"
    INCLUDE_DIRS "."
)
