// Stage table access.
//
// Every stage is generated by tools/gen_levels.py and lives in level_gen.c,
// ordered by a measured difficulty score. The hand-built stages that used to
// sit in front of them are gone: they were a fixed difficulty spliced onto the
// front of a ramp, which put a discontinuity exactly where the curve should
// have been gentlest. The generated set starts easy enough to learn on - stage
// 1 is one guard, one hostage, and no part of the route under watch.
#include "game.h"

int level_count(void)
{
    return g_level_gen_count;
}

const level_def_t *level_get(int idx)
{
    if (idx < 0) idx = 0;
    if (idx >= g_level_gen_count) idx = g_level_gen_count - 1;
    return &g_levels_gen[idx];
}
